### ISSUE TITLE
Display File Upload Url on Front-End

### ISSUE THREAD

**Issue by fatimawdesigns** [bainternet/My-Meta-Box#124]
I'm trying to link to a PDF I've uploaded. I'm a bit of a newbie at PHP but here's my code: 
```
 <a href="<?php $dwnld_pdf = get_post_meta($post->ID,'file_field_id',true);
 echo wp_get_attachment_url($dwnld_pdf); ?>" target="_blank">Download</a> 
```
Not sure what I'm doing wrong.

**Comment by fatimawdesigns** [comment]
It seems I've figured it out.

```
 <?php $dwnld_pdf = get_post_meta(get_the_ID(), 'file_field_id', true); ?>
 <a href="<?php echo $dwnld_pdf['url']; ?>" target="_blank" class="dwnld_btn"></a>
```

**Comment by ah-polash** [comment]
i am trying to get the url of the pdf file. I have wrote code below
<?php $saved_data=get_post_meta(get_the_ID(),'onei_pdf_file', true);  echo $saved_data['url'];?>
 in my php file. i am getting a warning telling 
 Warning:  Illegal string offset 'url' in <b>C:\xampp\htdocs\development\...\...........\file.php
Is there any solution ????
