### ISSUE TITLE
How can i use this value in file. 

### ISSUE THREAD

**Issue by OmarFaruque** [bainternet/My-Meta-Box#126]
In Admin panel plugin work good. but when i try to get data in the php file, i can't do this.

**Comment by bainternet** [comment]
is there a question or an issue you would like to report?

**Comment by mohamedhamad** [comment]
I think he's not sure how to get the post meta from the db in his templates.
Try this
` $value = get_post_meta($post_id, $prefix.'value_id'); `

**Comment by OmarFaruque** [comment]
Ok guys, i solved this problem.
