### ISSUE TITLE
big image in admin

### ISSUE THREAD

**Issue by MicrosoftGovno** [bainternet/My-Meta-Box#128]
![default](https://cloud.githubusercontent.com/assets/7033051/8762972/caff0fe4-2d91-11e5-9a47-d57f46c25962.PNG)

when upload image with width bigger than screen width, take place some bag.
Screenshot attached.

**Comment by mohamedhamad** [comment]
you need to update the css to make the image fit in the container.
`
td.at-field .simplePanelImagePreview img{
  max-width: 100% !important;
  height: auto;
}
`

**Comment by MicrosoftGovno** [comment]
thanks) fixed)
