### ISSUE TITLE
css issue with select2

### ISSUE THREAD

**Issue by fbaldo31** [bainternet/My-Meta-Box#130]
Hi, for the multiple select dropdown, the input class select2-input has a style width:20px it is problematic for displaying options to select.
I don't see where to change this.

**Comment by bainternet** [comment]
Its actually not a part of the class, you should look at select2 support for that.

https://select2.github.io/

**Comment by fbaldo31** [comment]
Sure ! Thank you

Cordialement,

Frédérick BALDO

2015-08-24 15:51 GMT+02:00 raz ohad <notifications@github.com>:
