### ISSUE TITLE
can't add addRepeaterBlock array inside other addRepeaterBlock

### ISSUE THREAD

**Issue by jnhghy** [bainternet/My-Meta-Box#131]
I'm trying to display repeatable fields inside other repeatable fields, I get fuzzy result here is my code:
  $tests_meta =  new AT_Meta_Box($config);

  $question_fields[] = $tests_meta->addText($prefix.'re_text_field_id',array('name'=> 'Answer '),true);
  $question_fields[] = $tests_meta->addCheckbox($prefix.'checkbox_field_id',array('name'=> 'Correct answer '));
  $question_fields[] = $tests_meta->addText($prefix.'re_text_field_id',array('name'=> 'Answer points '),true);
  $question_fields[] = $tests_meta->addText($prefix.'re_text_field_id',array('name'=> 'Hint For Answer '),true);

  $test_fields[] = $tests_meta->addText($prefix.'re_text_field_id',array('name'=> 'Question '),true);
  $test_fields[] = $tests_meta->addRepeaterBlock($prefix.'re_',array(
		    'inline'   => false, 
		    'name'     => 'Add Answer',
		    'fields'   => $question_fields, 
		    'sortable' => false
		  ));

  /*
   * Then just add the fields to the repeater block
   */
  //repeater block
  $tests_meta->addRepeaterBlock($prefix.'re_',array(
    'inline'   => false, 
    'name'     => 'Add qustion',
    'fields'   => $test_fields, 
    'sortable' => true
  ));

  $tests_meta->Finish();

![image](https://cloud.githubusercontent.com/assets/2087788/9776296/b35331de-575f-11e5-8859-8872876de378.png)

^this is the output
as you can see the fields are not displayed in the expected format.

Thank you and great job with this class, you are great!!!

**Comment by bainternet** [comment]
sadlly Its one of the class limitation, and will not work nor is it supported.
#21
