### ISSUE TITLE
Display the name name of select post field .. not the id

### ISSUE THREAD

**Issue by inkcreativ** [bainternet/My-Meta-Box#80]
Hi if someone could have helped me w/ this ...

``` PHP
<?php if(get_post_meta($post->ID,'_ink_artist_id',true)!='') { ?>
                <li><strong>Artist :</strong> 
                    <span>&nbsp;<?php echo get_post_meta( $post->ID, '_ink_artist_id', true );?></span>  
                 </li>
<?php } ?>
```

thxs

**Comment by Nanosergio** [comment]
First of all, thanks for this wonderful class.

This solution doesn't work for me :(

`$my_meta->addSelect($prefix.'select_concurso_destinatarios',array('destinatario1'=>'Estudiantes de Grado','destinatario2'=>'Estudiantes de Máster','destinatario3'=>'Estudiantes de Doctorado','destinatario4'=>'Estudiantes sin nivel especificado','selectkey5'=>'No especificado'),array('name'=> 'Destinatarios', 'multiple'=>true));`

`<?php echo get_post_meta( $post->ID, 'ba_select_concurso_destinatarios', true );?>`
Result: destinatario1

`<?php echo get_the_title(get_post_meta( $post->ID, 'ba_select_concurso_destinatarios', true ));?>`
Result:

It worked for post fields but not for select field.
